name: Main workflow
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4       
      - run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
      - name: Upload repo
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
  Linting:
    needs: Build
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download repo
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Run linter
        uses: super-linter/super-linter/slim@v5
        env:
          DEFAULT_BRANCH : main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


